name: Stack Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "cdk/**"
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_CDK_ROLE_ARN }}
          role-session-name: docs-site-template-deploy
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16
      - name: Installing dependencies
        working-directory: cdk
        run: npm install
      - name: Deployment
        working-directory: cdk
        env:
          CLI_ROLE_ARN: ${{ secrets.AWS_CLI_ROLE_ARN }}
        run: npm run deploy -- --require-approval never --outputs-file ./cdk-outputs.json
      - name: CDK Output
        id: cdk_output
        run: | 
          CDK_OUTPUT=$(cat cdk/cdk-outputs.json)
          echo "CDK Output:" >> $GITHUB_STEP_SUMMARY
          echo '```json' >> $GITHUB_STEP_SUMMARY
          echo "$CDK_OUTPUT" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "BucketName=$(echo $CDK_OUTPUT | grep BucketName | cut -d '"' -f 4)" >> $GITHUB_OUTPUT
          echo "DistributionId=$(echo $CDK_OUTPUT | grep DistributionId | cut -d '"' -f 4)" >> $GITHUB_OUTPUT
          echo "WebsiteUrl=$(echo $CDK_OUTPUT | grep WebsiteUrl | cut -d '"' -f 4)" >> $GITHUB_OUTPUT
      - name: Deploy dynamic secrets (BucketName)
        uses: dacbd/gha-secrets@v1
        with:
          token: ${{ secrets.GH_SECRETS_TOKEN }}
          name: AWS_BUCKET_NAME
          value: ${{ steps.cdk_output.outputs.BucketName }}
          location: repo
      - name: Deploy dynamic secrets (DistributionId)
        uses: dacbd/gha-secrets@v1
        with:
          token: ${{ secrets.GH_SECRETS_TOKEN }}
          name: AWS_DISTRIBUTION_ID
          value: ${{ steps.cdk_output.outputs.DistributionId }}
          location: repo
      - name: Deploy dynamic secrets (WebsiteUrl)
        uses: dacbd/gha-secrets@v1
        with:
          token: ${{ secrets.GH_SECRETS_TOKEN }}
          name: AWS_WEBSITE_URL
          value: ${{ steps.cdk_output.outputs.WebsiteUrl }}
          location: repo
      - name: Archive stack artifact
        uses: actions/upload-artifact@v3
        with:
          name: cdk-output
          path: |
            cdk/cdk-outputs.json
